{% set name = "stac-validator" %}
{% set version = "3.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/stac_validator-{{ version }}.tar.gz
  sha256: 816519ce03f2127fb8fe32542a5b874a348fc49912223661f8d545b247013bf4

build:
  entry_points:
    - stac-validator = stac_validator.stac_validator:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - click >=8.0.0
    - jsonschema >=3.2.0
    - python >={{ python_min }}
    - requests >=2.19.1
    - types-setuptools

test:
  imports:
    - stac_validator
  commands:
    - pip check
    - stac-validator --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/stac-utils/stac-validator
  summary: A package to validate STAC files
  license: Apache-2.0
  license_file: LICENSE
  doc_url: https://github.com/stac-utils/stac-validator
  dev_url: https://github.com/stac-utils/stac-validator

extra:
  recipe-maintainers:
    - gadomski
