{% set name = "stac-validator" %}
{% set version = "3.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/stac_validator-{{ version }}.tar.gz
  sha256: 4a5074504c81c07221b1a642606ae43cd40642490ffd4636f7257f6ea6b3c775

build:
  entry_points:
    - stac-validator = stac_validator.stac_validator:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - click >=8.0.0
    - jsonschema >=3.2.0
    - python >=3.7
    - requests >=2.19.1
    - types-setuptools

test:
  imports:
    - stac_validator
  commands:
    - pip check
    - stac-validator --help
  requires:
    - pip

about:
  home: https://github.com/stac-utils/stac-validator
  summary: A package to validate STAC files
  license: Apache-2.0
  license_file: LICENSE
  doc_url: https://github.com/stac-utils/stac-validator
  dev_url: https://github.com/stac-utils/stac-validator

extra:
  recipe-maintainers:
    - gadomski
